spring.application.name=vending-machine
server.port=8080
vending.external-api.base-url=http://localhost:3001
vending.coins.initial-inventory[10]=10
vending.coins.initial-inventory[20]=10
vending.coins.initial-inventory[50]=10
vending.coins.initial-inventory[100]=10
vending.coins.initial-inventory[200]=10
